# Generated by Django 5.2.11 on 2026-02-12 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_prescriptionimage_alter_cart_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(db_index=True, help_text="Ichki to'lov ID (unique)", max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('cash', 'Naqd')], db_index=True, help_text="To'lov provayderi", max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Jarayonda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Xato'), ('cancelled', 'Bekor qilindi'), ('refunded', 'Qaytarildi')], db_index=True, default='pending', help_text="To'lov holati", max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text="To'lov summasi (so'm)", max_digits=16)),
                ('click_trans_id', models.CharField(blank=True, db_index=True, help_text='Click transaction ID', max_length=255, null=True)),
                ('click_paydoc_id', models.CharField(blank=True, help_text='Click paydoc ID', max_length=255, null=True)),
                ('payme_transaction_id', models.CharField(blank=True, db_index=True, help_text='Payme transaction ID', max_length=255, null=True)),
                ('payme_time', models.BigIntegerField(blank=True, help_text='Payme transaction time (timestamp)', null=True)),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text="Provider javob ma'lumotlari")),
                ('error_message', models.TextField(blank=True, help_text='Xatolik xabari')),
                ('completed_at', models.DateTimeField(blank=True, help_text="To'lov yakunlangan vaqt", null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text="To'lov bekor qilingan vaqt", null=True)),
                ('order', models.ForeignKey(help_text='Buyurtma', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(help_text="To'lovchi foydalanuvchi", on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, help_text='prepare/complete/authorize/etc', max_length=50)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text="Provider'ga yuborilgan request")),
                ('response_data', models.JSONField(blank=True, default=dict, help_text="Provider'dan kelgan response")),
                ('error_message', models.TextField(blank=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='payments_pa_payment_6c9e39_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'status'], name='payments_pa_provide_cc7861_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payments_pa_order_i_1d1c93_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['click_trans_id'], name='payments_pa_click_t_2fb9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payme_transaction_id'], name='payments_pa_payme_t_b6391b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['payment', 'created_at'], name='payments_pa_payment_e94ce5_idx'),
        ),
    ]
