# Generated by Django 5.2.11 on 2026-02-10 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderpayment_orderstatushistory_prescription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ready', 'Yetkazishga tayyor'), ('on_the_way', 'Yo‘lda'), ('delivered', 'Yetkazildi'), ('canceled', 'Bekor qilindi')], db_index=True, default='ready', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Faol delivery (soft delete)')),
                ('courier_assigned_at', models.DateTimeField(blank=True, help_text='Kuryer real biriktirilgan vaqt', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Buyurtma yetkazilgan vaqt', null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='Operator yoki kuryer izohi')),
                ('courier', models.ForeignKey(blank=True, help_text='Biriktirilgan kuryer (ixtiyoriy)', limit_choices_to={'role': 'courier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(help_text='Yetkazishga tayyor buyurtma', on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='orders.order')),
            ],
            options={
                'verbose_name': 'Yetkazib berish',
                'verbose_name_plural': 'Yetkazib berishlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('ready', 'Yetkazishga tayyor'), ('on_the_way', 'Yo‘lda'), ('delivered', 'Yetkazildi'), ('canceled', 'Bekor qilindi')], max_length=20)),
                ('new_status', models.CharField(choices=[('ready', 'Yetkazishga tayyor'), ('on_the_way', 'Yo‘lda'), ('delivered', 'Yetkazildi'), ('canceled', 'Bekor qilindi')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='delivery.delivery')),
            ],
            options={
                'verbose_name': 'Delivery status tarixi',
                'verbose_name_plural': 'Delivery statuslar tarixi',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='delivery_de_status_6efeaa_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['courier', 'status'], name='delivery_de_courier_e5ae05_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('order',), name='unique_active_delivery_per_order'),
        ),
    ]
