# Generated by Django 5.2.11 on 2026-02-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smsverification',
            name='users_smsve_phone_n_b02147_idx',
        ),
        migrations.RemoveIndex(
            model_name='smsverification',
            name='users_smsve_created_489220_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='smsverification',
            index=models.Index(fields=['phone_number', 'created_at'], name='users_smsve_phone_n_0b243f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['verified_at'], name='users_user_verifie_3a4614_idx'),
        ),
    ]
