# Generated by Django 5.2.11 on 2026-02-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderpayment_orderstatushistory_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_order_i_5d347b_idx',
        ),
    ]
