# Generated by Django 5.2.11 on 2026-02-11 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('otp', 'Tasdiqlash kodi'), ('password_reset', 'Parol tiklash'), ('prescription_approved', 'Retsept tasdiqlandi'), ('prescription_rejected', 'Retsept rad etildi'), ('order_created', 'Buyurtma yaratildi'), ('order_awaiting_prescription', 'Retsept kutilmoqda'), ('order_awaiting_payment', 'Tolov kutilmoqda'), ('order_paid', 'Tolov qilindi'), ('order_preparing', 'Tayyorlanmoqda'), ('order_ready_for_delivery', 'Yetkazishga tayyor'), ('order_on_the_way', 'Yolda'), ('order_delivered', 'Yetkazildi'), ('order_cancelled', 'Bekor qilindi')], max_length=50, unique=True, verbose_name='Tur')),
                ('template_text', models.TextField(help_text='Shablon matni. Placeholder: {variable_name}', verbose_name='Shablon matni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Bildirishnoma shabloni',
                'verbose_name_plural': 'Bildirishnoma shablonlari',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=13, verbose_name='Telefon raqam')),
                ('code', models.CharField(max_length=4, verbose_name='Kod')),
                ('purpose', models.CharField(choices=[('registration', 'Royxatdan otish'), ('login', 'Tizimga kirish'), ('password_reset', 'Parol tiklash'), ('phone_verification', 'Telefon tasdiqlash')], max_length=30, verbose_name='Maqsad')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Amal qilish muddati')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Ishlatilgan')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Ishlatilgan vaqt')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Urinishlar')),
            ],
            options={
                'verbose_name': 'OTP Kod',
                'verbose_name_plural': 'OTP Kodlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'purpose', 'is_used'], name='notificatio_phone_n_ee2be0_idx'), models.Index(fields=['expires_at', 'is_used'], name='notificatio_expires_7523b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('otp', 'Tasdiqlash kodi'), ('password_reset', 'Parol tiklash'), ('prescription_approved', 'Retsept tasdiqlandi'), ('prescription_rejected', 'Retsept rad etildi'), ('order_created', 'Buyurtma yaratildi'), ('order_awaiting_prescription', 'Retsept kutilmoqda'), ('order_awaiting_payment', 'Tolov kutilmoqda'), ('order_paid', 'Tolov qilindi'), ('order_preparing', 'Tayyorlanmoqda'), ('order_ready_for_delivery', 'Yetkazishga tayyor'), ('order_on_the_way', 'Yolda'), ('order_delivered', 'Yetkazildi'), ('order_cancelled', 'Bekor qilindi')], db_index=True, max_length=50, verbose_name='Tur')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Telefon raqam')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xato'), ('cancelled', 'Bekor qilindi')], db_index=True, default='pending', max_length=20, verbose_name='Holat')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xato xabari')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Qoshimcha malumotlar')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Qayta urinishlar')),
                ('last_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi urinish vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_9a4505_idx'), models.Index(fields=['phone_number'], name='notificatio_phone_n_095130_idx')],
            },
        ),
    ]
