# Generated by Django 5.2.11 on 2026-02-12 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('otp', 'Tasdiqlash kodi'), ('password_reset', 'Parol tiklash'), ('prescription_approved', 'Retsept tasdiqlandi'), ('prescription_rejected', 'Retsept rad etildi'), ('order_created', 'Buyurtma yaratildi'), ('order_awaiting_prescription', 'Retsept kutilmoqda'), ('order_awaiting_payment', 'To‘lov kutilmoqda'), ('order_paid', 'To‘lov qilindi'), ('order_preparing', 'Tayyorlanmoqda'), ('order_ready_for_delivery', 'Yetkazishga tayyor'), ('order_on_the_way', 'Yo‘lda'), ('order_delivered', 'Yetkazildi'), ('order_cancelled', 'Bekor qilindi')], max_length=60)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push'), ('system', 'System (In-App)')], default='sms', max_length=20)),
                ('template_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('notification_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push'), ('system', 'System (In-App)')], db_index=True, default='system', max_length=20)),
                ('notification_type', models.CharField(choices=[('otp', 'Tasdiqlash kodi'), ('password_reset', 'Parol tiklash'), ('prescription_approved', 'Retsept tasdiqlandi'), ('prescription_rejected', 'Retsept rad etildi'), ('order_created', 'Buyurtma yaratildi'), ('order_awaiting_prescription', 'Retsept kutilmoqda'), ('order_awaiting_payment', 'To‘lov kutilmoqda'), ('order_paid', 'To‘lov qilindi'), ('order_preparing', 'Tayyorlanmoqda'), ('order_ready_for_delivery', 'Yetkazishga tayyor'), ('order_on_the_way', 'Yo‘lda'), ('order_delivered', 'Yetkazildi'), ('order_cancelled', 'Bekor qilindi')], db_index=True, max_length=60)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Yuborilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xato'), ('cancelled', 'Bekor qilindi')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_9a4505_idx'), models.Index(fields=['channel', 'status'], name='notificatio_channel_289841_idx')],
            },
        ),
    ]
