# Generated by Django 5.2.11 on 2026-02-11 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPCode',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_phone_n_095130_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='last_retry_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push'), ('system', 'System (In-App)')], db_index=True, default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push'), ('system', 'System (In-App)')], default='sms', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('otp', 'Tasdiqlash kodi'), ('password_reset', 'Parol tiklash'), ('prescription_approved', 'Retsept tasdiqlandi'), ('prescription_rejected', 'Retsept rad etildi'), ('order_created', 'Buyurtma yaratildi'), ('order_awaiting_prescription', 'Retsept kutilmoqda'), ('order_awaiting_payment', 'To‘lov kutilmoqda'), ('order_paid', 'To‘lov qilindi'), ('order_preparing', 'Tayyorlanmoqda'), ('order_ready_for_delivery', 'Yetkazishga tayyor'), ('order_on_the_way', 'Yo‘lda'), ('order_delivered', 'Yetkazildi'), ('order_cancelled', 'Bekor qilindi')], db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='notification',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='notification',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Yuborilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xato'), ('cancelled', 'Bekor qilindi')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('otp', 'Tasdiqlash kodi'), ('password_reset', 'Parol tiklash'), ('prescription_approved', 'Retsept tasdiqlandi'), ('prescription_rejected', 'Retsept rad etildi'), ('order_created', 'Buyurtma yaratildi'), ('order_awaiting_prescription', 'Retsept kutilmoqda'), ('order_awaiting_payment', 'To‘lov kutilmoqda'), ('order_paid', 'To‘lov qilindi'), ('order_preparing', 'Tayyorlanmoqda'), ('order_ready_for_delivery', 'Yetkazishga tayyor'), ('order_on_the_way', 'Yo‘lda'), ('order_delivered', 'Yetkazildi'), ('order_cancelled', 'Bekor qilindi')], max_length=60),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_text',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('notification_type', 'channel')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel', 'status'], name='notificatio_channel_289841_idx'),
        ),
    ]
