# Generated by Django on 2026-02-12

from django.db import migrations


def create_notification_templates(apps, schema_editor):
    """Create default notification templates for OTP and Orders"""
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    
    # OTP SMS Template - DevSMS APPROVED FORMAT
    NotificationTemplate.objects.get_or_create(
        notification_type='otp',
        channel='sms',
        defaults={
            'template_text': "Dorixona tizimi: ro'yxatdan o'tish uchun tasdiqlash kodingiz {code}",
            'is_active': True,
        }
    )
    
    # OTP System Template
    NotificationTemplate.objects.get_or_create(
        notification_type='otp',
        channel='system',
        defaults={
            'template_text': 'Tasdiqlash kodi: {code}',
            'is_active': True,
        }
    )
    
    # Order Created Template
    NotificationTemplate.objects.get_or_create(
        notification_type='order_created',
        channel='system',
        defaults={
            'template_text': 'Buyurtmangiz #{order_id} qabul qilindi. Jami: {total_price} som',
            'is_active': True,
        }
    )
    
    # Order Paid Template
    NotificationTemplate.objects.get_or_create(
        notification_type='order_paid',
        channel='system',
        defaults={
            'template_text': 'Buyurtma #{order_id} uchun tolov qabul qilindi.',
            'is_active': True,
        }
    )
    
    # Order Ready for Delivery Template
    NotificationTemplate.objects.get_or_create(
        notification_type='order_ready_for_delivery',
        channel='system',
        defaults={
            'template_text': 'Buyurtmangiz #{order_id} yetkazishga tayyor.',
            'is_active': True,
        }
    )
    
    # Prescription Approved Template
    NotificationTemplate.objects.get_or_create(
        notification_type='prescription_approved',
        channel='system',
        defaults={
            'template_text': 'Retseptingiz tasdiqlandi.',
            'is_active': True,
        }
    )
    
    # Prescription Rejected Template
    NotificationTemplate.objects.get_or_create(
        notification_type='prescription_rejected',
        channel='system',
        defaults={
            'template_text': 'Retseptingiz rad etildi. Sabab: {reason}',
            'is_active': True,
        }
    )


def reverse_templates(apps, schema_editor):
    """Remove templates if migration is reversed"""
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    NotificationTemplate.objects.filter(
        notification_type__in=[
            'otp',
            'order_created',
            'order_paid',
            'order_ready_for_delivery',
            'prescription_approved',
            'prescription_rejected',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),  # Update this to match your latest migration
    ]

    operations = [
        migrations.RunPython(create_notification_templates, reverse_templates),
    ]
