# Generated by Django 5.2.11 on 2026-02-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_create_default_templates'),
        ('notifications', '0002_delete_otpcode_alter_notification_options_and_more'),
    ]

    operations = [
    ]
